// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package i18n

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p := messageKeyToIndex[key]
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"en": &dictionary{index: enIndex, data: enData},
		"zh": &dictionary{index: zhIndex, data: zhData},
	}
	fallback := language.MustParse("en")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
	"Error business version too low: src[%s] --> dest[%s]":                      3,
	"Error cannot find the business: %s":                                        1,
	"Error channel key[%s] is empty":                                            8,
	"Error does not exists this channel. id: %s":                                7,
	"Error emtpy business: %s":                                                  2,
	"Error finding the peer. address: %s":                                       9,
	"Error invoke succeeded but the response status was not 200 (response: %s)": 0,
	"Error peer already joined this channel: %s":                                12,
	"Error this peer address is not included in the channel peers. address: %s": 10,
	"Invalid channel create transaction : %s":                                   4,
	"Peer joined successfully. address: %s":                                     11,
	"genesis block file not found %s":                                           5,
	"proposal failed (err: %s)":                                                 6,
}

var enIndex = []uint32{ // 14 elements
	0x00000000, 0x0000004d, 0x00000073, 0x0000008f,
	0x000000ca, 0x000000f5, 0x00000118, 0x00000135,
	0x00000163, 0x00000185, 0x000001ac, 0x000001f9,
	0x00000222, 0x00000250,
} // Size: 80 bytes

const enData string = "" + // Size: 592 bytes
	"\x02Error invoke succeeded but the response status was not 200 (response" +
	": %[1]s)\x02Error cannot find the business: %[1]s\x02Error emtpy busines" +
	"s: %[1]s\x02Error business version too low: src[%[1]s] --> dest[%[2]s]" +
	"\x02Invalid channel create transaction : %[1]s\x02genesis block file not" +
	" found %[1]s\x02proposal failed (err: %[1]s)\x02Error does not exists th" +
	"is channel. id: %[1]s\x02Error channel key[%[1]s] is empty\x02Error find" +
	"ing the peer. address: %[1]s\x02Error this peer address is not included " +
	"in the channel peers. address: %[1]s\x02Peer joined successfully. addres" +
	"s: %[1]s\x02Error peer already joined this channel: %[1]s"

var zhIndex = []uint32{ // 14 elements
	0x00000000, 0x00000039, 0x0000005a, 0x00000072,
	0x000000b6, 0x000000d7, 0x000000f9, 0x0000011a,
	0x00000138, 0x00000152, 0x00000188, 0x000001d0,
	0x000001f7, 0x0000021b,
} // Size: 80 bytes

const zhData string = "" + // Size: 539 bytes
	"\x02调用成功但响应状态不是200（响应：%[1]s）\x02错误无法找到业务：%[1]s\x02错误空业务：%[1]s\x02错误业务版本太" +
	"低：原版本[%[1]s] --> 目标版本[%[2]s]\x02渠道创建交易无效：%[1]s\x02未找到genesis block fil" +
	"e %[1]s\x02提案失败（错误：%[1]s）\x02此通道不存在. id: %[1]s\x02渠道key[%[1]s]值为空\x02按地址" +
	"查找节点时发生错误。地址：%[1]s\x02错误此节点地址未包含在通道节点地址中。地址：%[1]s\x02节点成功加入链。地址：%[1]s" +
	"\x02错误节点已加入此链：%[1]s"

	// Total table size 1291 bytes (1KiB); checksum: 1F10A558
