// Code generated by protoc-gen-go. DO NOT EDIT.
// source: algorithm.proto

package tee

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Algorithm struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Hash                 string   `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	FileId               string   `protobuf:"bytes,4,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	Description          string   `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Owner                string   `protobuf:"bytes,6,opt,name=owner,proto3" json:"owner,omitempty"`
	CreateSeconds        int64    `protobuf:"varint,7,opt,name=create_seconds,json=createSeconds,proto3" json:"create_seconds,omitempty"`
	UpdateSeconds        int64    `protobuf:"varint,8,opt,name=update_seconds,json=updateSeconds,proto3" json:"update_seconds,omitempty"`
	Signatures           []string `protobuf:"bytes,9,rep,name=signatures,proto3" json:"signatures,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Algorithm) Reset()         { *m = Algorithm{} }
func (m *Algorithm) String() string { return proto.CompactTextString(m) }
func (*Algorithm) ProtoMessage()    {}
func (*Algorithm) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c381a4f1e580eed, []int{0}
}

func (m *Algorithm) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Algorithm.Unmarshal(m, b)
}
func (m *Algorithm) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Algorithm.Marshal(b, m, deterministic)
}
func (m *Algorithm) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Algorithm.Merge(m, src)
}
func (m *Algorithm) XXX_Size() int {
	return xxx_messageInfo_Algorithm.Size(m)
}
func (m *Algorithm) XXX_DiscardUnknown() {
	xxx_messageInfo_Algorithm.DiscardUnknown(m)
}

var xxx_messageInfo_Algorithm proto.InternalMessageInfo

func (m *Algorithm) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Algorithm) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Algorithm) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *Algorithm) GetFileId() string {
	if m != nil {
		return m.FileId
	}
	return ""
}

func (m *Algorithm) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Algorithm) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *Algorithm) GetCreateSeconds() int64 {
	if m != nil {
		return m.CreateSeconds
	}
	return 0
}

func (m *Algorithm) GetUpdateSeconds() int64 {
	if m != nil {
		return m.UpdateSeconds
	}
	return 0
}

func (m *Algorithm) GetSignatures() []string {
	if m != nil {
		return m.Signatures
	}
	return nil
}

func init() {
	proto.RegisterType((*Algorithm)(nil), "tee.Algorithm")
}

func init() { proto.RegisterFile("algorithm.proto", fileDescriptor_8c381a4f1e580eed) }

var fileDescriptor_8c381a4f1e580eed = []byte{
	// 211 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0xd0, 0xc1, 0x4a, 0x03, 0x31,
	0x10, 0x06, 0x60, 0x76, 0xb7, 0xdd, 0x9a, 0x11, 0x2b, 0x0c, 0x82, 0x73, 0x92, 0x20, 0x08, 0x7b,
	0xf2, 0xe2, 0x13, 0x78, 0xf4, 0xba, 0x3e, 0x40, 0x89, 0x9b, 0xb1, 0x3b, 0xd0, 0x26, 0x4b, 0x92,
	0xe2, 0xdd, 0x27, 0x2f, 0x49, 0x28, 0xec, 0x6d, 0xfe, 0xef, 0xff, 0x4f, 0x03, 0x8f, 0xe6, 0x74,
	0xf4, 0x41, 0xd2, 0x7c, 0x7e, 0x5f, 0x82, 0x4f, 0x1e, 0xbb, 0xc4, 0xfc, 0xfa, 0xdf, 0x82, 0xfa,
	0xbc, 0x15, 0xb8, 0x87, 0x56, 0x2c, 0x35, 0xba, 0x19, 0xd4, 0xd8, 0x8a, 0x45, 0x84, 0x8d, 0x33,
	0x67, 0xa6, 0xb6, 0x48, 0xb9, 0xb3, 0xcd, 0x26, 0xce, 0xd4, 0x55, 0xcb, 0x37, 0x3e, 0xc3, 0xee,
	0x57, 0x4e, 0x7c, 0x10, 0x4b, 0x9b, 0xc2, 0x7d, 0x8e, 0x5f, 0x16, 0x35, 0xdc, 0x5b, 0x8e, 0x53,
	0x90, 0x25, 0x89, 0x77, 0xb4, 0x2d, 0xe5, 0x9a, 0xf0, 0x09, 0xb6, 0xfe, 0xcf, 0x71, 0xa0, 0xbe,
	0x74, 0x35, 0xe0, 0x1b, 0xec, 0xa7, 0xc0, 0x26, 0xf1, 0x21, 0xf2, 0xe4, 0x9d, 0x8d, 0xb4, 0xd3,
	0xcd, 0xd0, 0x8d, 0x0f, 0x55, 0xbf, 0x2b, 0xe6, 0xd9, 0x65, 0xb1, 0xeb, 0xd9, 0x5d, 0x9d, 0x55,
	0xbd, 0xcd, 0x5e, 0x00, 0xa2, 0x1c, 0x9d, 0x49, 0x97, 0xc0, 0x91, 0x94, 0xee, 0x06, 0x35, 0xae,
	0xe4, 0xa7, 0x2f, 0x0f, 0xf9, 0xb8, 0x06, 0x00, 0x00, 0xff, 0xff, 0xb6, 0x52, 0x34, 0x4e, 0x23,
	0x01, 0x00, 0x00,
}
